name: mengo_delivery
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.8.4
  nb_utils: ^6.0.0
  google_fonts: ^5.1.0
  cached_network_image: ^3.2.3
  dio: ^5.2.1+1
  shared_preferences: ^2.2.0
  image_picker: ^1.0.1
  permission_handler: ^10.4.3
  url_launcher: ^6.1.12
  share_plus: ^7.0.2
  connectivity_plus: ^4.0.1
  path_provider: ^2.1.1
  intl: ^0.18.0
  babstrap_settings_screen: ^0.1.6
  carousel_slider: ^4.2.1
  modal_bottom_sheet: ^3.0.0-pre
  bottom_picker: ^2.0.4
  cherry_toast: ^1.5.3



  msh_checkbox: ^2.0.1
  overlay_loader_with_app_icon: ^0.0.3
  iconoir_flutter: ^6.11.0
  flutter_launcher_icons: ^0.13.1
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2
  selector_wheel: ^1.1.2
  dio_cache_interceptor: ^3.4.4
  dio_cache_interceptor_hive_store: ^3.2.1
  pusher_client_fixed: ^0.0.2+2
  firebase_messaging: ^14.7.4
  flutter_local_notifications: ^16.1.0
  firebase_core: ^2.22.0
  # laravel_echo_null: ^0.0.5+7
  # pusher_beams: ^1.1.1
  path: ^1.8.3
  http_parser: ^4.0.2
  flutter_easyloading: ^3.0.5
  easy_localization: ^3.0.3
  restart_app: ^1.2.1
  timeline_tile_nic: ^2.0.1
  lottie: ^2.7.0
  flutter_phone_direct_caller: ^2.1.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Myanmar
      fonts:
        - asset: assets/fonts/MyanmarGantGaw.ttf

  assets:
    - assets/icons/
    - assets/language/
    - assets/images/
    - assets/translations/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 2
