name: mengo_delivery
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.8.4
  nb_utils: ^6.0.0
  google_fonts: ^5.1.0
  cached_network_image: ^3.2.3
  dio: ^5.2.1+1
  shared_preferences: ^2.2.0
  image_picker: ^1.0.1
  permission_handler: ^10.4.3
  url_launcher: ^6.1.12
  share_plus: ^7.0.2
  connectivity_plus: ^4.0.1
  path_provider: ^2.0.15
  intl: ^0.18.0
  flutter_icon_snackbar: ^1.1.4
  babstrap_settings_screen: ^0.1.6
  dot_navigation_bar: ^1.0.2
  carousel_slider: ^4.2.1
  modal_bottom_sheet: ^3.0.0-pre
  bottom_picker: ^2.0.4



  msh_checkbox: ^2.0.1

  iconoir_flutter: ^6.11.0
  flutter_launcher_icons: ^0.13.1
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2
  lottie: ^2.6.0
  loader_overlay: ^2.3.2
  selector_wheel: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Myanmar
      fonts:
        - asset: assets/fonts/MyanmarGantGaw.ttf

  assets:
    - assets/icons/
    - assets/language/
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 2
